version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./ddl:/ddl"
    environment:
      - POSTGRES_PASSWORD=password

  # see: https://github.com/prest/prest/blob/master/docker-compose.yml
  prest:
    image: prest/prest
    ports:
      - "6000:3000"
    environment:
      - PREST_DEBUG=true
      - PREST_PG_HOST=postgres
      - PREST_PG_PORT=5432
      - PREST_PG_USER=postgres
      - PREST_PG_PASS=password
      - PREST_PG_DATABASE=testdb
      - PREST_JWT_DEFAULT=false
    depends_on:
      - postgres

