debug = true

[pg]
  host = "postgres"
  port = 5432
  user = "postgres"
  pass = "password"
  database = "testdb"

[cors]
  alloworigin = ["http://localhost:3000"]

[jwt]
  default = false

[ssl]
  mode = "disable"

[queries]
  location = "/queries"

